/**
 * Generated by orval v6.12.1 🍺
 * Do not edit manually.
 * Certificate Authority API
 * A simple API for managing certificates
 * OpenAPI spec version: 0.0.1
 */

export interface CreateUserDto {
  email: string | null;
  firstName: string | null;
  lastName: string | null;
  name: string;
  password: string;
  roles: string[] | null;
}
