/**
 * Generated by orval v6.12.1 🍺
 * Do not edit manually.
 * Certificate Authority API
 * A simple API for managing certificates
 * OpenAPI spec version: 0.0.1
 */

export interface ErrorDto {
  /** The error code */
  code: number;
  /** The error as string */
  error: string;
  /** The error message.
Only returned in debug mode. */
  message?: string | null;
}
