FROM rust:1-alpine as build
WORKDIR /app/backend
COPY backend .
COPY shared /app/shared
RUN apk add pkgconfig openssl-dev gcc musl-dev perl make
RUN cargo build --release

FROM alpine:3
WORKDIR /app
COPY --from=build /app/backend/target/release/ca-backend .
EXPOSE 8080
CMD ["./ca-backend"]