/**
 * Generated by orval v6.12.1 🍺
 * Do not edit manually.
 * Certificate Authority API
 * A simple API for managing certificates
 * OpenAPI spec version: 0.0.1
 */

export interface CACertificateDto {
	/** The certificate pem string */
	certificate: string;
	/** The time the certificate was created */
	createdAt: string;
	/** The time the certificate is valid until */
	validUntil: string;
}
