/**
 * Generated by orval v6.12.1 🍺
 * Do not edit manually.
 * Certificate Authority API
 * A simple API for managing certificates
 * OpenAPI spec version: 0.0.1
 */

export type DeleteUserParams = {
	/**
 * Whether to delete the user rather than just deactivating it.
Defaults to false.
 */
	deleteInDatabase?: boolean;
};
