/**
 * Generated by orval v6.12.1 🍺
 * Do not edit manually.
 * Certificate Authority API
 * A simple API for managing certificates
 * OpenAPI spec version: 0.0.1
 */

export interface HealthInfoDto {
	/** The current version of keycloak */
	keycloakVersion?: string | null;
	/** Whether the API is up and running */
	ok: boolean;
	/** The current status of the API */
	status: string;
	/** The current version of the API */
	version: string;
}
