/**
 * Generated by orval v6.12.1 🍺
 * Do not edit manually.
 * Certificate Authority API
 * A simple API for managing certificates
 * OpenAPI spec version: 0.0.1
 */

/**
 * A certificate signing request
 */
export interface NewSigningRequestDto {
  /** Alternative names for the certificate */
  alternativeNames?: string[] | null;
  /** The client certificate */
  request: string;
}
