/**
 * Generated by orval v6.12.1 🍺
 * Do not edit manually.
 * Certificate Authority API
 * A simple API for managing certificates
 * OpenAPI spec version: 0.0.1
 */

export interface CACertificateDto {
	/** The certificate pem string */
	certificate: string;
	/** The time the certificate was created */
	createdAt: string;
	/** The private key of the certificate
This is only returned if the certificate is the root certificate
and has just been created. */
	privateKey?: string | null;
	/** Whether the certificate is the root certificate */
	root: boolean;
	/** The time the certificate is valid until */
	validUntil: string;
}
