/**
 * Generated by orval v6.12.1 🍺
 * Do not edit manually.
 * Certificate Authority API
 * A simple API for managing certificates
 * OpenAPI spec version: 0.0.1
 */

export interface ClientDto {
	/** Whether the client is active */
	active: boolean;
	/** The time the client was created */
	createdAt: string;
	/** The client display name */
	displayName: string;
	/** The client id */
	id: string;
	/** The client name */
	name: string;
	/** The client token. Only returned when creating a new client. */
	token?: string | null;
	/** The client token hash */
	tokenHash: string;
	/** The time the client was last updated */
	updatedAt: string;
	/** The id of the user that owns the client */
	userId: string;
	/** The time the client is valid until */
	validUntil?: string | null;
}
