/**
 * Generated by orval v6.12.1 🍺
 * Do not edit manually.
 * Certificate Authority API
 * A simple API for managing certificates
 * OpenAPI spec version: 0.0.1
 */

export type ListClientsParams = {
	/**
 * Whether to include inactive clients in the result.
Defaults to false.
 */
	includeInactive?: boolean | null;
};
