/**
 * Generated by orval v6.12.1 🍺
 * Do not edit manually.
 * Certificate Authority API
 * A simple API for managing certificates
 * OpenAPI spec version: 0.0.1
 */

export interface UserDto {
	active: boolean;
	createdAt: string;
	displayName: string;
	email: string | null;
	firstName: string | null;
	id: string;
	lastName: string | null;
	name: string;
	roles: string[];
	updatedAt: string;
}
